### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by morpheouss** [belliash/AerScript#1]
Hi there, 

It seems that Aerscript is very similar to PHP, but with strict type hinting. All I miss in PH7 are namespaces.
Can you provide namespace support?

**Comment by belliash** [comment]
Although AerScript is based on PH7 Engine, it is not compatible with PHP, nor PH7. Its syntax is very similar to all C-like language family. During language development, many constructions have changed. Actually they are way less or more similar to C# (eg. 'is', '??' operators, static classes). What is more PH7 is not compatible with PHP. Tt mimics PHP. The array by references is probably a huge woe for porting code from PHP to PH7.

AerScript is not trying to fix PH7 or to extend it, but to provide completely new language, that aims to fix all (most?) PHP problems. You can read about them here: https://webonastick.com/php.html Of course namespace support is on the TODO list, but I cannot provide you the estimated time of delivery. You have to be patient.

**Comment by morpheouss** [comment]
PH7 implements PHP virtual machine with some Symisc extensions. All my scripts well work under PH7. All I miss is namespace.
AerScript is based on PH7 with some additional extensions. I think i can customize my script to work under AerScript. I Just need namespaces.

**Comment by belliash** [comment]
Symisc claims that PH7 Engine is an implementation of PHP language, but when you read details about that language, you will notice that this is not really a truth. I have already specified one example. In PHP, all arrays are passed by value, while in PH7 they are passed by reference. This is a huge woe for porting code from PHP to PH7. Another example is ternary operator, which behaves differently. I know that it is broken in PHP and Symisc claims that they fixed it. This is all right, but since the same code gives different output in PHP and PH7, you cannot say that PH7 Engine implements PHP, or some subset of PHP. This is basically a PHP-like implementation with some enhancements. Unfortunately PH7 is very buggy piece of code and Symisc seems to does not care about the community. There is no engine code change within last 4 years. Many errors have been reported, some patches provided, and none of them have been fixed, nor pulled into repository.
Some of them have been fixed in AerScript already, but still I must remark, that AerScript is not PHP and it is not going to be compatible with it. There are still many things to do and with every commit, porting code from PHP to AerScript will be harder and harder. Until there are still many bugs and problems that I need to fix in PH7 Engine, I am trying to not focus on new features, especially those big features requiring changes in all components. Namespace is such a feature, thus do not expect it to come soon. There is no plan to add namespace support to first official, public AerScript release. Anyway it is still on my TODO list.
